services:
  - type: web
    name: snapshot-mern
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd mern && npm install && cd client && npm install && npm run build && cd ../server && npm install && cd ../..
    startCommand: cd mern/server && node server.js
    envVars:
      - key: ATLAS_URI
        scope: build
        value: $ATLAS_URI
